# What is Feature Scaling?

Feature scaling is a technique to standardize the independent features presnt in the data in a fixed range

# Types of Feature Scaling

1. Standardization

2. Normalization (min-max scaler )

# Standardization Code Example On a Social Networks Ads DataSet

In [11]:
import numpy as np

In [12]:
import pandas as pd

In [13]:
import matplotlib.pyplot as plt

In [14]:
import seaborn as sns

In [15]:
df = pd.read_csv("Social_Network_Ads.csv")

In [16]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [17]:
df = df.iloc[:, 2:] #All rows and columns number 2 and ownward needed remaining droped

In [18]:
df.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

# Train Test Split

The train_test_split function in machine learning is primarily used to split a dataset into two subsets: a training set and a testing set.

In [19]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.drop('Purchased', axis=1), df['Purchased'], test_size=0.3, random_state=0)

In [20]:
x_train.shape, x_test.shape

((280, 2), (120, 2))

# Standard Scaller

In [21]:
from sklearn.preprocessing import StandardScaler

In [22]:
scaler = StandardScaler()

In [23]:
scaler.fit(x_train)

StandardScaler()

# Transform Train and Testsets

In [24]:
x_train_scaled = scaler.transform(x_train)

In [25]:
x_test_scaled = scaler.transform(x_test)

In [26]:
scaler.mean_

array([3.78642857e+01, 6.98071429e+04])

In [29]:
x_train_scaled = pd.DataFrame(x_train_scaled, columns = x_train.columns)

In [30]:
x_test_scaled = pd.DataFrame(x_test_scaled, columns = x_test.columns)

In [31]:
np.round(x_train.describe(),1)

Age  EstimatedSalary
count  280.0            280.0
mean    37.9          69807.1
std     10.2          34641.2
min     18.0          15000.0
25%     30.0          43000.0
50%     37.0          70500.0
75%     46.0          88000.0
max     60.0         150000.0

In [32]:
np.round(x_train_scaled.describe(),1)

Age  EstimatedSalary
count  280.0            280.0
mean     0.0              0.0
std      1.0              1.0
min     -1.9             -1.6
25%     -0.8             -0.8
50%     -0.1              0.0
75%      0.8              0.5
max      2.2              2.3

# Why Scaling is Important?

In [33]:
from sklearn.linear_model import LogisticRegression

In [34]:
lr = LogisticRegression()
lr_scaled = LogisticRegression()

In [35]:
lr.fit(x_train,y_train)
lr_scaled.fit(x_train_scaled, y_train)

LogisticRegression()

In [36]:
y_pred = lr.predict(x_test)
y_pred_scaled = lr_scaled.predict(x_test_scaled)

In [37]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [38]:
y_pred_scaled

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1], dtype=int64)

In [39]:
from sklearn.metrics import accuracy_score

In [40]:
print("Actual", accuracy_score(y_test, y_pred))

print("scaled", accuracy_score(y_test, y_pred_scaled))

Actual 0.6583333333333333
scaled 0.8666666666666667


we see that without feature scaling techniques we get the 65% accuracy by using logistic regression and 86% accuracy after feature scaling so it is clear that feature scaling is important to getb the model performance