### Our text to be vectorized 

In [2]:
paragraph = """Khan was born in Lahore on 5 October 1952.
Some reports suggest he was born on 25 November 1952.
It was reported that 25 November was wrongly mentioned by Pakistan Cricket Board officials on his passport. 
He is the only son of Ikramullah Khan Niazi, a civil engineer, and his wife Shaukat Khanum, and has four sisters.
Long settled in Mianwali in northwestern Punjab, his paternal family are of Pashtun ethnicity and belong to the 
Niazi tribe,and one of his ancestors, Haibat Khan Niazi, in the 16th century, "was one of Sher Shah Suri's leading generals, 
as well as being the governor of Punjab. Like his father, Khan's mother was an ethnic Pashtun, who belonged 
to the Burki tribe and whose ancestors had been settled in the Jalandhar district of Punjab for centuries. 
Following the creation of Pakistan, she migrated to Lahore with the rest of Khan's maternal relatives. 
Khan's maternal family has produced a number of cricketers, including those who have represented Pakistan,
such as his cousins Javed Burki and Majid Khan. Maternally, Khan is also a descendant of the Sufi warrior-poet 
and inventor of the Pashto alphabet,Pir Roshan, who hailed from his maternal family's ancestral Kaniguram town 
located in South Waziristan in the tribal areas of northwest Pakistan. His maternal family was based in Basti Danishmanda,
Jalandhar, India for about 600 years. A quiet and shy boy in his youth, Khan grew up with his sisters in relatively
affluent, upper middle-class circumstances and received a privileged education. He was educated at the Aitchison College
and Cathedral School in Lahore,and then the Royal Grammar School Worcester in England, where he excelled at cricket.
In 1972, he enrolled in Keble College, Oxford where he studied Philosophy, Politics and Economics, graduating in 1975.
An enthusiast for college cricket at Keble, Paul Hayes, was instrumental in securing the admission of Khan,after he had
been turned down by Cambridge."""


In [3]:
import nltk

### Breaking paragraph at sentence level

In [5]:
sentences = nltk.sent_tokenize(paragraph)
# print each sentence seaprately 
print(len(sentences))
for sent in sentences:
    print(sent)
    print()

14
Khan was born in Lahore on 5 October 1952.

Some reports suggest he was born on 25 November 1952.

It was reported that 25 November was wrongly mentioned by Pakistan Cricket Board officials on his passport.

He is the only son of Ikramullah Khan Niazi, a civil engineer, and his wife Shaukat Khanum, and has four sisters.

Long settled in Mianwali in northwestern Punjab, his paternal family are of Pashtun ethnicity and belong to the 
Niazi tribe,and one of his ancestors, Haibat Khan Niazi, in the 16th century, "was one of Sher Shah Suri's leading generals, 
as well as being the governor of Punjab.

Like his father, Khan's mother was an ethnic Pashtun, who belonged 
to the Burki tribe and whose ancestors had been settled in the Jalandhar district of Punjab for centuries.

Following the creation of Pakistan, she migrated to Lahore with the rest of Khan's maternal relatives.

Khan's maternal family has produced a number of cricketers, including those who have represented Pakistan,
such a

#### Using regular expression for dropping all text except capital and small characters and numbersfrom  0 to 9 

In [8]:
# import string 
# punctuations = string.punctuation
# print(punctuations)

# def remove_punc(text):
#     refined_text = ""
#     for char in text:
#         if char not in punctuations:
#             refined_text +=char
#     return refined_text



# print(remove_punc(paragraph))





import re
corpus = []
for sent in sentences:
    corpus.append(re.sub('[^a-zA-Z0-9]'," ",sent).lower())
print(corpus)

['khan was born in lahore on 5 october 1952 ', 'some reports suggest he was born on 25 november 1952 ', 'it was reported that 25 november was wrongly mentioned by pakistan cricket board officials on his passport ', 'he is the only son of ikramullah khan niazi  a civil engineer  and his wife shaukat khanum  and has four sisters ', 'long settled in mianwali in northwestern punjab  his paternal family are of pashtun ethnicity and belong to the  niazi tribe and one of his ancestors  haibat khan niazi  in the 16th century   was one of sher shah suri s leading generals   as well as being the governor of punjab ', 'like his father  khan s mother was an ethnic pashtun  who belonged  to the burki tribe and whose ancestors had been settled in the jalandhar district of punjab for centuries ', 'following the creation of pakistan  she migrated to lahore with the rest of khan s maternal relatives ', 'khan s maternal family has produced a number of cricketers  including those who have represented pak

### Printing each doc in corpus separately just to view 


In [9]:
for doc_number, corp in enumerate(corpus):
    print(f"{doc_number} {corp}")

0 khan was born in lahore on 5 october 1952 
1 some reports suggest he was born on 25 november 1952 
2 it was reported that 25 november was wrongly mentioned by pakistan cricket board officials on his passport 
3 he is the only son of ikramullah khan niazi  a civil engineer  and his wife shaukat khanum  and has four sisters 
4 long settled in mianwali in northwestern punjab  his paternal family are of pashtun ethnicity and belong to the  niazi tribe and one of his ancestors  haibat khan niazi  in the 16th century   was one of sher shah suri s leading generals   as well as being the governor of punjab 
5 like his father  khan s mother was an ethnic pashtun  who belonged  to the burki tribe and whose ancestors had been settled in the jalandhar district of punjab for centuries 
6 following the creation of pakistan  she migrated to lahore with the rest of khan s maternal relatives 
7 khan s maternal family has produced a number of cricketers  including those who have represented pakistan  

# Use of stemmer to convert the original word to base word and filtering stopwords 

In [11]:
from nltk.corpus import stopwords
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [19]:
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()
stemmer.stem("sung")

'sung'

In [20]:
from nltk.stem import PorterStemmer  # allows to redefine the word on its root word
from nltk.corpus import stopwords    # are the words that donot have direct impact on semantics of documents 

stemmer = PorterStemmer()
stemmed_corpus = []
stop_words = []
# separating words and stop words and applying stemming on words.
for sent in corpus:
    stemmed_doc = ""
    words = nltk.word_tokenize(sent)
    for word in words:
        if word not in stopwords.words('english'):
            stemmed_doc +=stemmer.stem(word)+ " "
        else:
            stop_words.append(word)
    stemmed_corpus.append(stemmed_doc)
stemmed_corpus

['khan born lahor 5 octob 1952 ',
 'report suggest born 25 novemb 1952 ',
 'report 25 novemb wrongli mention pakistan cricket board offici passport ',
 'son ikramullah khan niazi civil engin wife shaukat khanum four sister ',
 'long settl mianwali northwestern punjab patern famili pashtun ethnic belong niazi tribe one ancestor haibat khan niazi 16th centuri one sher shah suri lead gener well governor punjab ',
 'like father khan mother ethnic pashtun belong burki tribe whose ancestor settl jalandhar district punjab centuri ',
 'follow creation pakistan migrat lahor rest khan matern rel ',
 'khan matern famili produc number cricket includ repres pakistan cousin jave burki majid khan ',
 'matern khan also descend sufi warrior poet inventor pashto alphabet pir roshan hail matern famili ancestr kaniguram town locat south waziristan tribal area northwest pakistan ',
 'matern famili base basti danishmanda jalandhar india 600 year ',
 'quiet shi boy youth khan grew sister rel affluent upper m

### all the words other-than stop words after applying stemming 

In [21]:
for stemmedword in stemmed_corpus:
    print(stemmedword, end=" ")

khan born lahor 5 octob 1952  report suggest born 25 novemb 1952  report 25 novemb wrongli mention pakistan cricket board offici passport  son ikramullah khan niazi civil engin wife shaukat khanum four sister  long settl mianwali northwestern punjab patern famili pashtun ethnic belong niazi tribe one ancestor haibat khan niazi 16th centuri one sher shah suri lead gener well governor punjab  like father khan mother ethnic pashtun belong burki tribe whose ancestor settl jalandhar district punjab centuri  follow creation pakistan migrat lahor rest khan matern rel  khan matern famili produc number cricket includ repres pakistan cousin jave burki majid khan  matern khan also descend sufi warrior poet inventor pashto alphabet pir roshan hail matern famili ancestr kaniguram town locat south waziristan tribal area northwest pakistan  matern famili base basti danishmanda jalandhar india 600 year  quiet shi boy youth khan grew sister rel affluent upper middl class circumst receiv privileg educ  

### Example to unserstand what a stemmer do

In [22]:
stemmer.stem("history")
#base word

'histori'

### all the filtered stop words after applying stemming

In [23]:
for stopwords in stop_words:
    print(stopwords,end=" ")

was in on some he was on it was that was by on his he is the only of a and his and has in in his are of and to the and of his in the was of s as as being the of his s was an who to the and had been in the of for the of she to with the of s s has a of those who have such as his and is a of the and of the who from his s in in the of his was in for about a and in his up with his in and a he was at the and in and then the in where he at in he in where he and in an for at was in the of after he had been down by 

### Using lemmatizer to get the meaningful word of a word

In [24]:
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer

[nltk_data] Downloading package wordnet to C:\Users\Nasir
[nltk_data]     Hussain\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [27]:
lemmatizer = WordNetLemmatizer()
lemmatizer.lemmatize("worngli")
#returns meaning ful word 

'worngli'

In [28]:
stemmed_corpus

['khan born lahor 5 octob 1952 ',
 'report suggest born 25 novemb 1952 ',
 'report 25 novemb wrongli mention pakistan cricket board offici passport ',
 'son ikramullah khan niazi civil engin wife shaukat khanum four sister ',
 'long settl mianwali northwestern punjab patern famili pashtun ethnic belong niazi tribe one ancestor haibat khan niazi 16th centuri one sher shah suri lead gener well governor punjab ',
 'like father khan mother ethnic pashtun belong burki tribe whose ancestor settl jalandhar district punjab centuri ',
 'follow creation pakistan migrat lahor rest khan matern rel ',
 'khan matern famili produc number cricket includ repres pakistan cousin jave burki majid khan ',
 'matern khan also descend sufi warrior poet inventor pashto alphabet pir roshan hail matern famili ancestr kaniguram town locat south waziristan tribal area northwest pakistan ',
 'matern famili base basti danishmanda jalandhar india 600 year ',
 'quiet shi boy youth khan grew sister rel affluent upper m

In [29]:
stemmed_lemmatized_corpus=[]
for corp in stemmed_corpus:
    lemmatized_doc = ""
    words = nltk.word_tokenize(corp)
    
    for word in words:
        lemmatized_doc +=lemmatizer.lemmatize(word)+ " "        
    stemmed_lemmatized_corpus.append(lemmatized_doc)

print(stemmed_lemmatized_corpus)
    

['khan born lahor 5 octob 1952 ', 'report suggest born 25 novemb 1952 ', 'report 25 novemb wrongli mention pakistan cricket board offici passport ', 'son ikramullah khan niazi civil engin wife shaukat khanum four sister ', 'long settl mianwali northwestern punjab patern famili pashtun ethnic belong niazi tribe one ancestor haibat khan niazi 16th centuri one sher shah suri lead gener well governor punjab ', 'like father khan mother ethnic pashtun belong burki tribe whose ancestor settl jalandhar district punjab centuri ', 'follow creation pakistan migrat lahor rest khan matern rel ', 'khan matern famili produc number cricket includ repres pakistan cousin jave burki majid khan ', 'matern khan also descend sufi warrior poet inventor pashto alphabet pir roshan hail matern famili ancestr kaniguram town locat south waziristan tribal area northwest pakistan ', 'matern famili base basti danishmanda jalandhar india 600 year ', 'quiet shi boy youth khan grew sister rel affluent upper middl class

### A short example to understad whats going on 

In [39]:
#https://www.geeksforgeeks.org/using-countvectorizer-to-extracting-features-from-text/
from sklearn.feature_extraction.text import CountVectorizer

document = ["One Geek helps Two Geeks",
            "Two Geeks help Four Geeks",
            "Each Geek helps many other Geeks at Geeks for Geeks"]

# Create a Vectorizer Object
vectorizer = CountVectorizer(binary=True,ngram_range=(1, 3))#binary means if count of a word is 2 it will give 1 as presenece is marked. 

vectorizer.fit(document)

vocab = vectorizer.vocabulary_
# Printing the identified Unique words along with their indices
print("Vocabulary: ", vocab)
print(len(vocab))

# Encode the Document
vector = vectorizer.transform(document)

# Summarizing the Encoded Texts
print("Encoded Document is:")
print(vector.toarray())


Vocabulary:  {'one': 32, 'geek': 10, 'helps': 24, 'two': 38, 'geeks': 14, 'one geek': 33, 'geek helps': 11, 'helps two': 27, 'two geeks': 39, 'one geek helps': 34, 'geek helps two': 13, 'helps two geeks': 28, 'help': 21, 'four': 8, 'geeks help': 19, 'help four': 22, 'four geeks': 9, 'two geeks help': 40, 'geeks help four': 20, 'help four geeks': 23, 'each': 3, 'many': 29, 'other': 35, 'at': 0, 'for': 6, 'each geek': 4, 'helps many': 25, 'many other': 30, 'other geeks': 36, 'geeks at': 15, 'at geeks': 1, 'geeks for': 17, 'for geeks': 7, 'each geek helps': 5, 'geek helps many': 12, 'helps many other': 26, 'many other geeks': 31, 'other geeks at': 37, 'geeks at geeks': 16, 'at geeks for': 2, 'geeks for geeks': 18}
41
Encoded Document is:
[[0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 1 1 1 0
  0 0 1 1 0]
 [0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 1 1 1]
 [1 1 1 1 1 1 1 1 0 0 1 1 1 0 1 1 1 1 1 0 0 0 0 0 1 1 1 0 0 1 1 1 0 0 0 1
  1 1 0

Vocabulary:  {'one': 9, 'geek': 4, 'helps': 7, 'two': 11, 'geeks': 5, 'help': 6, 'four': 3, 'each': 1, 'many': 8, 'other': 10, 'at': 0, 'for': 2}

Encoded Document is:

[[0 0 0 0 1 1 0 1 0 1 0 1]

 [0 0 0 1 0 1 1 0 0 0 0 1]
 
 [1 1 1 0 1 1 0 1 1 0 1 0]]

In [42]:
from sklearn.feature_extraction.text import CountVectorizer
binary_BOW_vectorizer= CountVectorizer(stop_words='english',binary=True)

#we can apply ngrams methods in BOW by just passing ngram parameter 

In [46]:
# test code now implemeted above 
# from nltk.stem import PoerStemmer  # allows to redefine the word on its root word
# from nltk.corpus import stopwordsrt    # are the words that donot have direct impact on semantics of documents 

# stemmer = PorterStemmer()
# stemmed_corpus = []
# stop_words = []
# # separating words and stop words and applying stemming on words.
# for sent in corpus:
#     doc = ""
#     words = nltk.word_tokenize(sent)
#     for word in words:
#         if word not in stopwords.words('english'):
#             doc +=stemmer.stem(word)+ " "
            
#         else:
#             stop_words.append(word)
#     stemmed_corpus.append(doc)

# print(stemmed_corpus)

In [47]:
X = binary_BOW_vectorizer.fit_transform(stemmed_lemmatized_corpus)
X

<14x130 sparse matrix of type '<class 'numpy.int64'>'
	with 174 stored elements in Compressed Sparse Row format>

In [45]:
vocabulary  = binary_BOW_vectorizer.vocabulary_
vocabulary

{'khan': 61,
 'born': 17,
 'lahor': 63,
 'octob': 80,
 '1952': 1,
 'report': 99,
 'suggest': 116,
 '25': 4,
 'novemb': 78,
 'wrongli': 127,
 'mention': 70,
 'pakistan': 83,
 'cricket': 29,
 'board': 16,
 'offici': 81,
 'passport': 86,
 'son': 112,
 'ikramullah': 52,
 'niazi': 75,
 'civil': 24,
 'engin': 35,
 'wife': 125,
 'shaukat': 108,
 'khanum': 62,
 'sister': 111,
 'long': 67,
 'settl': 106,
 'mianwali': 71,
 'northwestern': 77,
 'punjab': 95,
 'patern': 87,
 'famili': 41,
 'pashtun': 85,
 'ethnic': 39,
 'belong': 15,
 'tribe': 120,
 'ancestor': 10,
 'haibat': 49,
 '16th': 0,
 'centuri': 22,
 'sher': 109,
 'shah': 107,
 'suri': 117,
 'lead': 64,
 'gener': 44,
 'governor': 45,
 'like': 65,
 'father': 42,
 'mother': 74,
 'burki': 19,
 'jalandhar': 57,
 'district': 32,
 'follow': 43,
 'creation': 28,
 'migrat': 73,
 'rest': 101,
 'matern': 69,
 'rel': 98,
 'produc': 94,
 'number': 79,
 'includ': 53,
 'repres': 100,
 'cousin': 27,
 'jave': 58,
 'majid': 68,
 'descend': 31,
 'sufi': 115

In [100]:
len(vocabulary)

130

In [48]:
print(X[0].toarray())
print(X[10].toarray().shape)
print(X[12].toarray().shape)
print(X[3].toarray().shape)

[[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
(1, 130)
(1, 130)
(1, 130)


In [102]:
print(1, corpus[0])
print(2, corpus[1])
print(3,corpus[2])
print(4, corpus[3])

1 khan was born in lahore on 5 october 1952 
2 some reports suggest he was born on 25 november 1952 
3 it was reported that 25 november was wrongly mentioned by pakistan cricket board officials on his passport 
4 he is the only son of ikramullah khan niazi  a civil engineer  and his wife shaukat khanum  and has four sisters 


In [49]:
for i, code in enumerate(X[0].toarray()[0]):
    if code==1:
        print(i,code)
        


1 1
17 1
61 1
63 1
80 1


In [111]:
sentences

['Khan was born in Lahore on 5 October 1952.',
 'Some reports suggest he was born on 25 November 1952.',
 'It was reported that 25 November was wrongly mentioned by Pakistan Cricket Board officials on his passport.',
 'He is the only son of Ikramullah Khan Niazi, a civil engineer, and his wife Shaukat Khanum, and has four sisters.',
 'Long settled in Mianwali in northwestern Punjab, his paternal family are of Pashtun ethnicity and belong to the Niazi tribe,and one of his ancestors, Haibat Khan Niazi, in the 16th century, "was one of Sher Shah Suri\'s leading generals, as well as being the governor of Punjab.',
 "Like his father, Khan's mother was an ethnic Pashtun, who belonged to the Burki tribe and whose ancestors had been settled in the Jalandhar district of Punjab for centuries.",
 "Following the creation of Pakistan, she migrated to Lahore with the rest of Khan's maternal relatives.",
 "Khan's maternal family has produced a number of cricketers, including those who have represente

## All the above applied process in one code 

In [65]:

import re
from nltk.corpus import stopwords
corpus = []
for i in range(len(sentences)):
    review = re.sub('[^a-zA-Z0-9]',' ',sentences[i]).lower().split()
    
    review=[lemmatizer.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
    review=[stemmer.stem(word) for word in review]
    
    review = ' '.join(review)
    
    corpus.append(review)
corpus

['khan born lahor 5 octob 1952',
 'report suggest born 25 novemb 1952',
 'report 25 novemb wrongli mention pakistan cricket board offici passport',
 'son ikramullah khan niazi civil engin wife shaukat khanum four sister',
 'long settl mianwali northwestern punjab patern famili pashtun ethnic belong niazi tribe one ancestor haibat khan niazi 16th centuri one sher shah suri lead gener well governor punjab',
 'like father khan mother ethnic pashtun belong burki tribe whose ancestor settl jalandhar district punjab centuri',
 'follow creation pakistan migrat lahor rest khan matern rel',
 'khan matern famili produc number cricket includ repres pakistan cousin jave burki majid khan',
 'matern khan also descend sufi warrior poet inventor pashto alphabet pir roshan hail matern famili ancestr kaniguram town locat south waziristan tribal area northwest pakistan',
 'matern famili base basti danishmanda jalandhar india 600 year',
 'quiet shi boy youth khan grew sister rel affluent upper middl class

# TFIDF

In [66]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [67]:
cv = TfidfVectorizer()
X = cv.fit_transform(stemmed_lemmatized_corpus)

In [68]:
stemmed_lemmatized_corpus[0]

'khan born lahor 5 octob 1952 '

In [69]:
X[0].toarray()

array([[0.        , 0.47583065, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.47583065, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.25628637, 0.        ,
        0.42337187, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.  

In [112]:
cv = TfidfVectorizer(ngram_range=(3,3))
X = cv.fit_transform(stemmed_lemmatized_corpus)
X[0].toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.57735027,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.57735027, 0.        , 0.  

In [71]:
cv = TfidfVectorizer(ngram_range=(3,3),max_features=10)
X = cv.fit_transform(stemmed_lemmatized_corpus)
X[0].toarray()

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
#!pip install gensim

In [ ]:
import gensim

In [ ]:
from gensim.models import Word2Vec, KeyedVectors